name: Build
on: [push]
jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: cachix/install-nix-action@v12
          with:
            install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
            extra_nix_config:
              experimental-features = nix-command flakes
        - run: nix build
        - uses: crazy-max/ghaction-github-pages@v2
          with:
             build_dir: result
             target_branch: gh-pages
             keep_history: true
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
